const SignActionTypes = {
  SHOW_SIGNIN_COMPONENT: 'SHOW_SIGNIN_COMPONENT',
  SHOW_SIGNUP_COMPONENT: 'SHOW_SIGNUP_COMPONENT',
  HIDDEN_SIGN_COMPONENT: 'HIDDEN_SIGN_COMPONENT',
}

export default SignActionTypes;