const MenuActionTypes = {
  FETCH_MENU_DATA_START: 'FETCH_MENU_DATA_START',
  FETCH_MENU_DATA_SUCCESS: 'FETCH_MENU_DATA_SUCCESS',
  FETCH_MENU_DATA_FAILURE: 'FETCH_MENU_DATA_FAILURE',
  TOGGLE_MENU_DATA: 'TOGGLE_MENU_DATA',
};

export default MenuActionTypes;
