const MenuActionTypes = {
  FETCH_MENU_DATA_START: 'FETCH_MENU_DATA_START',
  FETCH_MENU_DATA_SUCCESS: 'FETCH_MENU_DATA_SUCCESS',
  FETCH_MENU_DATA_FAILURE: 'FETCH_MENU_DATA_FAILURE',
  TOGGLE_MENU_DATA_TO_NOTE: 'TOGGLE_MENU_DATA_TO_NOTE',
  TOGGLE_MENU_DATA_TO_START_UP: 'TOGGLE_MENU_DATA_TO_START_UP'
};

export default MenuActionTypes;
